config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

admin.site.site_header = 'Awesome Inc. Administration'
admin.site.site_title = 'Awesome Inc. Administration'

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('django_learning.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here

    url(r'^boards/', include('django_learning.boards.urls', namespace='boards')),
    url(r'^cars/', include('django_learning.cars.urls', namespace='cars')),
    url(r'^api/', include('django_learning.api.urls', namespace='api')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

django_learning/cars/urls.py
from django.conf.urls import url

from .views import UserCarDetailView, UserCarsViewList, FuelHistoryList, FuelHistoryAdd

app_name = 'cars'

urlpatterns = [
    url(r'^$', UserCarsViewList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', UserCarDetailView.as_view(), name='detail'),
    url(r'^fuel/$', FuelHistoryList.as_view(), name='fuel_list'),
    url(r'^(?P<pk>\d+)/fuel/$', FuelHistoryList.as_view(), name='fuel_list'),
    url(r'^fuel/pay/$', FuelHistoryAdd.as_view(), name='fuel_add'),
    url(r'^(?P<pk>\d+)/fuel/pay/$', FuelHistoryAdd.as_view(), name='fuel_add'),
]

django_learning/cars/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import ugettext_lazy as _


class FuelType(models.Model):
    value = models.CharField(max_length=25, verbose_name=_('fuel type'))

    class Meta:
        verbose_name = 'Тип топлива'
        verbose_name_plural = 'Типы топлива'

    def __str__(self):
        return '{}'.format(self.value)

class Fuel(models.Model):
    name = models.CharField(max_length=10, verbose_name=_('fuel name'))
    descriptions = models.CharField(max_length=256, verbose_name=_('fuel descriptions'))
    type = models.ForeignKey(FuelType, verbose_name=_('fuel type'))

    class Meta:
        verbose_name = 'Марка топлива'
        verbose_name_plural = 'Марки топлива'

    def __str__(self):
        return '{} {}'.format(self.type, self.name)


class Car(models.Model):
    manufacturer = models.CharField(max_length=256, verbose_name=_('car manufacturer'))
    model = models.CharField(max_length=256, verbose_name=_('car model'))
    fuel_type = models.ForeignKey(FuelType, blank=True, null=True, verbose_name=_('car fuel type'))
    fuel = models.ManyToManyField(Fuel, blank=True, verbose_name=_('car fuel'))

    def __str__(self):
        return '{} {}'.format(self.manufacturer, self.model)

    class Meta:
        verbose_name = 'Автомобиль'
        verbose_name_plural = 'Автомобили'

    @property
    def get_grade_of_fuel(self):
        grade_of_fuel = self.fuel.all()
        if grade_of_fuel:
            return "{}".format(', '.join([fuel for fuel in grade_of_fuel.values_list('name', flat=True)]))
        else:
            return _("N/A")


class UserCars(models.Model):
    car = models.ForeignKey(Car, verbose_name=_('User car'))
    user = models.ForeignKey('users.User', verbose_name=_('User'))

    def __str__(self):
        return '{} {}({})-{} {}'.format(
            self.user.first_name,
            self.user.last_name,
            self.user.username,
            self.car.manufacturer,
            self.car.model
        )

    class Meta:
        verbose_name = 'Автомобиль пользователя'
        verbose_name_plural = 'Автомобили пользователя'


class FuelHistory(models.Model):
    car = models.ForeignKey(UserCars, null=False, blank=False,
                            verbose_name='Автомобиль')
    count = models.DecimalField(null=True, blank=True,
                                max_digits=7, decimal_places=2,
                                verbose_name='Количество')
    date = models.DateTimeField(null=False, blank=False,
                                verbose_name='Дата заправки')
    fuel = models.ForeignKey(Fuel, null=False, blank=False,
                                  verbose_name='Тип топлива')
    cost = models.DecimalField(null=True, blank=True,
                               max_digits=7, decimal_places=2,
                               verbose_name='Цена за литр')
    total_cost = models.DecimalField(null=True, blank=True,
                                     max_digits=7, decimal_places=2,
                                     verbose_name='Стоимость')

    class Meta:
        verbose_name = 'История заправок'
        verbose_name_plural = 'История заправок'

    def __str__(self):
        return '{} - {} - {} - {}'.format(
            self.date.date(),
            self.car,
            self.fuel,
            self.count,
        )

    def get_absolute_url(self):
        return reverse('cars:fuel_list', kwargs={'pk': self.car.id})


class FuelMileage(models.Model):
    mileage = models.DecimalField(max_digits=6, decimal_places=2, verbose_name=_('mileage'))
    fuel_history = models.ManyToManyField(FuelHistory, blank=True, verbose_name=_('dressing'))

    class Meta:
        verbose_name = _('mileage between refueling')
        verbose_name_plural = _('mileage between refueling')

    def __str__(self):
        return '{}'.format(self.mileage)

django_learning/cars/forms.py
from django.forms import forms
from django.forms.models import ModelForm

from .models import Car, FuelHistory, UserCars, FuelMileage


class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = ('manufacturer', 'model', 'fuel_type', 'fuel')


class FuelHistoryAddForm(ModelForm):
    class Meta:
        model = FuelHistory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(FuelHistoryAddForm, self).__init__(*args, **kwargs)
        initial = kwargs.get('initial')
        if initial:
            user = initial.get('user')
            if user:
                self.fields['car'].queryset = UserCars.objects.filter(user=user)

    def clean(self):
        cleaned_data = super(FuelHistoryAddForm, self).clean()
        cost = cleaned_data.get('cost', None)
        total_cost = cleaned_data.get('total_cost', None)
        count = cleaned_data.get('count', None)

        if count:
            if cost and total_cost:
                if total_cost != cost * count:
                    self.add_error('cost', 'Цена за литр не соответствует стоимости')
                    self.add_error('total_cost', 'Стоимость не соответствует цене за литр')
            elif cost and not total_cost:
                tmp_total_cost = cost * count
                cleaned_data['total_cost'] = tmp_total_cost
            elif not cost and total_cost:
                tmp_cost = total_cost / count
                cleaned_data['cost'] = tmp_cost
            else:
                self.add_error(None, 'Укажите цену за литр или стоимость')
                self.add_error('cost', '')
                self.add_error('total_cost', '')
        else:
            if cost and total_cost:
                cur_count = round(total_cost / cost, 2)
                cleaned_data['count'] = cur_count
            elif cost and not total_cost:
                self.add_error('total_cost', 'Что бы посчитать количество нужно указать стоимость')
            elif not cost and total_cost:
                self.add_error('cost', 'Что бы посчитать количество нужно указать цену за литр')
            else:
                self.add_error(None, 'Укажите количество, цену за литр или стоимость')
                self.add_error('count', '')
                self.add_error('cost', '')
                self.add_error('total_cost', '')

        return cleaned_data


class FuelMileageForm(forms.Form):
    class Meta:
        model = FuelMileage
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(FuelMileageForm, self).__init__(*args, **kwargs)

django_learning/cars/views.py
import datetime

from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Max

from .models import Car, UserCars, FuelHistory
from .forms import CarForm, FuelHistoryAddForm


class UserCarsViewList(LoginRequiredMixin, ListView):
    model = UserCars
    template_name = 'cars/cars_list.html'

    def get_queryset(self):
        qs = UserCars.objects.filter(user=self.request.user)
        return qs


class UserCarDetailView(LoginRequiredMixin, DetailView):
    model = UserCars
    template_name = 'cars/car_detail.html'

    def get_queryset(self):
        qs = super(UserCarDetailView, self).get_queryset()
        qs.filter(user=self.request.user)
        return qs


class FuelHistoryList(LoginRequiredMixin, ListView):
    model = FuelHistory
    template_name = 'cars/fuel_list.html'

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        kwargs = {'car__user': self.request.user}
        if pk:
            kwargs['car__pk'] = pk
        return FuelHistory.objects.filter(**kwargs)

    def get_context_data(self, **kwargs):
        context = super(FuelHistoryList, self).get_context_data(**kwargs)
        context['car_id'] = self.kwargs.get('pk')
        qs = self.get_queryset()
        aggregate = qs.aggregate(count=Sum('count'), total=Sum('total_cost'))
        if aggregate != {'count': None, 'total': None}:
            context['aggregate'] = aggregate
        return context


class FuelHistoryAdd(LoginRequiredMixin, CreateView):
    model = FuelHistory
    form_class = FuelHistoryAddForm
    template_name = 'cars/fuel_pay.html'

    def get_initial(self):
        date = datetime.datetime.now()
        car = UserCars.objects.filter(pk=self.kwargs.get('pk'), user=self.request.user).first()
        result = {
            'user': self.request.user,
            'date': date,
        }
        if car:
            fuel = car.car.fuel.all().first()
            result['car'] = car
            result['fuel'] = fuel
        return result

django_learning/cars/templates/cars/car_detail.html
{% extends "cars/cars_base.html" %}
{% load static django_bootstrap_breadcrumbs %}

{% block title %}Car: {{ object.car }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Cars" "cars:list" %}
    {% breadcrumb object.car "cars:detail" object.id %}
    {% breadcrumb "View" "edit" %}
{% endblock %}

{% block content %}
    <dl class="row">
        <dt class="col-sm-3" style="text-align: right">Производитель</dt>
        <dd class="col-sm-9">
            {{ object.car.manufacturer }}
        </dd>
        <dt class="col-sm-3" style="text-align: right">Марка</dt>
        <dd class="col-sm-9">
            {{ object.car.model }}
        </dd>
        <dt class="col-sm-3" style="text-align: right">Тип топлива</dt>
        <dd class="col-sm-9">
            {{ object.car.fuel_type }}
        </dd>
        <dt class="col-sm-3" style="text-align: right">Марка топлива</dt>
        <dd class="col-sm-9">
            {{ object.car.get_grade_of_fuel }}
        </dd>
    </dl>
{% endblock content %}

django_learning/cars/templates/cars/cars_base.html
{% extends "base.html" %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
{% endblock %}

django_learning/cars/templates/cars/cars_list.html
{% extends "cars/cars_base.html" %}
{% load static i18n django_bootstrap_breadcrumbs %}
{% block title %}Cars{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Cars" "cars:list" %}
    {% breadcrumb "All" "cars:list" %}
{% endblock %}

{% block content %}
    <div class="table-responsive">
        <table class="table table-sm">
            <thead class="thead-default">
                <tr>
                    <th>#</th>
                    <th>Manufacturer</th>
                    <th>Model</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for car in object_list %}
                <tr>
                    <th scope="row">
                        {{ forloop.counter }}
                    </th>
                    <td>
                        {{ car.car.manufacturer }}
                    </td>
                    <td>
                        {{ car.car.model }}
                    </td>
                    <td>
                        <a href="{% url 'cars:detail' car.id %}" role="button" class="btn btn-outline-info btn-sm">
                            Подробнее
                        </a>
                    </td>
                    <td>
                        <a role="button" class="btn btn-outline-info btn-sm" href="{% url 'cars:fuel_list' car.id %}">fuel list</a>
                        <a role="button" class="btn btn-outline-info btn-sm" href="{% url 'cars:fuel_add' car.id %}">add fuel</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot class="thead-default">
                <tr>
                    <th colspan="4">&nbsp;</th>
                    <th>
                        <a role="button" class="btn btn-outline-info btn-sm" href="{% url 'cars:fuel_list' %}">All fuel list</a>
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>
{% endblock content %}

django_learning/cars/templates/cars/fuel_list.html
{% extends 'cars/cars_base.html' %}


{% block content %}
    <div class="row">
        <a role="button" class="btn btn-primary" href="{% if car_id %}{% url 'cars:fuel_add' car_id %}{% else %}{% url 'cars:fuel_add' %}{% endif %}">Add</a>
    </div>
    <div class="row">
        <table class="table table-sm">
            <thead class="thead-default">
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Car</th>
                    <th>Count</th>
                    <th>Cost</th>
                    <th>Total cost</th>
                </tr>
            </thead>
            <tbody>
                {% for fuel in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ fuel.date }}</td>
                        <td>{{ fuel.car.car }}</td>
                        <td>{{ fuel.count }}</td>
                        <td>{{ fuel.cost }}</td>
                        <td>{{ fuel.total_cost }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            {% if aggregate %}
                <tfoot class="thead-default">
                    <tr>
                        <td>#</td>
                        <td colspan="2">Total</td>
                        <td>{{ aggregate.count }}</td>
                        <td></td>
                        <td>{{ aggregate.total }}</td>
                    </tr>
                </tfoot>
            {% endif %}
        </table>
    </div>
{% endblock %}

django_learning/cars/templates/cars/fuel_pay.html
{% extends 'cars/cars_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-submit">Записать</button>
    </form>
{% endblock %}